apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-service:9090
        isDefault: true
        version: 1
        editable: true
        uid: PBFA97CFB590B2093