apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: validator-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

  selector:
    matchLabels:
      type: local  