apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geth-ingress
  namespace: ethereum 
spec:
  rules:
    - host: ethssv.com 
      http:
        paths:
          - path: /rpc
            pathType: Prefix
            backend:
              service:
                name: geth-service
                port:
                  number: 8545
          - path: /geth-rpc
            pathType: Prefix
            backend:
              service:
                name: geth-service
                port:
                  number: 8551
