apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geth-ingress
  namespace: ethereum
spec:
  rules:
    - host: eth.ssv.com  # Replace 'your.domain.com' with your actual domain name
      http:
        paths:
          - path: /geth  # This is the path that will be routed to your NodePort Service
            pathType: Prefix
            backend:
              service:
                name: geth-service
                port:
                  number: 8551






















# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: geth-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#   namespace: ethereum 
# spec:
#   rules:
#     - host: ethssv.com 
#       http:
#         paths:
#         # - pathType: Prefix
#         - path: "/rpc"
#           backend:
#             service:
#               name: geth-service
#               port: 8551

           
#           #         number: 8545
#           # - path: /geth-rpc
#           #   pathType: Prefix
#           #   backend:
#           #     service:
#           #       name: geth-service
#           #       port:
#           #         number: 8551
