apiVersion: v1
kind: Service
metadata:
  name: geth-service
spec:
  selector:
    app: geth
  ports:
    - protocol: TCP
      name: eth-tcp
      port: 30303
      targetPort: 30303
    - protocol: UDP
      name: eth-udp
      port: 30303
      targetPort: 30303
    - protocol: TCP
      name: rpc
      port: 8545
      targetPort: 8545
    - protocol: TCP
      name: websocket
      port: 8546
      targetPort: 8546
    - protocol: TCP
      name: eth
      port: 12000
      targetPort: 12000
    - protocol: TCP
      name: eth1
      port: 9100
      targetPort: 9100
    - protocol: TCP
      name: ethereum
      port: 6060
      targetPort: 6060
    - protocol: TCP
      name: geth-rpc
      port: 8551
      targetPort: 8551
      # nodePort: 32111
  type: NodePort
