apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: geth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: ethereum 
spec:
  rules:
    - host: ethssv.com 
      http:
        paths:
        - path: /rpc
          backend:
             serviceName: geth-service
             servicePort: 8551

           
          #         number: 8545
          # - path: /geth-rpc
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: geth-service
          #       port:
          #         number: 8551
