apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deployment
  labels:
    app: geth
spec:
  selector:
    matchLabels:
      app: geth
  replicas: 1
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: ethereum/client-go:stable
        volumeMounts:
        - name: eth-storage
          mountPath: /home/eth_storage/
        - name: jwt-secret-volume
          mountPath: /secrets/jwtsecret
          subPath: jwtsecret
          readOnly: true  
        ports:
        - containerPort: 30303
          protocol: UDP
        - containerPort: 30303
          protocol: TCP
        - containerPort: 8545
          protocol: TCP
        - containerPort: 8546
          protocol: TCP
        - containerPort: 12000
          protocol: TCP
        - containerPort: 9100
          protocol: TCP
        - containerPort: 6161
          protocol: TCP  
        - containerPort: 8551
          protocol: TCP
        args:
          - --goerli
          - --http.addr
          - 0.0.0.0
          - --ws
          - --ws.origins
          - "*"
          - --ws.addr
          - 0.0.0.0
          - --ws.port=8546
          - --authrpc.addr 
          - 0.0.0.0 
          - --authrpc.port=8551
          - --authrpc.vhosts
          - "*"
          - --http
          - --metrics
          - --metrics.addr=0.0.0.0
          - --metrics.port=6161
          - --pprof
          - --datadir
          - /home/eth_storage/geth_storage
          - --authrpc.jwtsecret   # Add the flag here
          - /secrets/jwtsecret   # Path to the JWT secret file inside the mounted ConfigMap volume
      volumes:
      - name: eth-storage
        hostPath:
          path: /home/eth_storage/
      - name: jwt-secret-volume
        secret:
          secretName: jwt-secret