apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # This should match or be less than the PV capacity
  selector:
    matchLabels:
      type: local