apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
  namespace: ethereum 
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${NAME}  #specify the region of aws here.
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret     #awssm-secret,secret name which we have created when we add credintial for aws
            key: access-key
            namespace: default
          secretAccessKeySecretRef:
            name: aws-secret     #awssm-secret,secret name which we have created when we add credintial for aws
            key: secret-access-key
            namespace: default
#this file  create general store for external secret