apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'codelab-monitor'
    scrape_configs:
      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter-service:9100']
      - job_name: 'geth'
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /debug/metrics/prometheus
        scheme: http
        static_configs:
          - targets: ['geth-service:6161']
      - job_name: 'beacon node'
        static_configs:
          - targets: ['prysm-service:8585']
      - job_name: 'ssv'
        metrics_path: /metrics
        static_configs:
          - targets: ['ssv-node-service:15000']