apiVersion: v1
kind: Service
metadata:
  name: ssv-node-service
spec:
  selector:
    app: ssv-node
  ports:
    - name: tcp-port
      protocol: TCP
      port: 13001
      targetPort: 13001
    - name: udp-port
      protocol: UDP
      port: 12001
      targetPort: 12001
  type: ClusterIP
