apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssv-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssv-node
  template:
    metadata:
      labels:
        app: ssv-node
    spec:
      containers:
      - name: ssv-node
        image: bloxstaking/ssv-node:latest
        args:
        - make
        - BUILD_PATH=/go/bin/ssvnode
        - start-node
        env:
        - name: CONFIG_PATH
          value: /etc/config/config.yaml  # Update the path inside the container
        ports:
        - containerPort: 13001
          protocol: TCP
        - containerPort: 12001
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config  # Update the mount path inside the container
        - name: data-volume
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: ssv-config  # Use the ConfigMap we created earlier
      - name: data-volume
        hostPath:
          path: /home/eth_storage/
