apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: ethereum 

spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: operatorPrivateKeyKubernetes