apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eth-staking-infra
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rahilmansuri1/argocd-kubernetes.git
    targetRevision: eth_staking
    path: eth-staking/menifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: eth-staking

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
