apiVersion: v1
kind: PersistentVolume
metadata:
  name: geth-pv
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 10Gi  # Adjust this as needed also adjust in PVC
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu"  # This will use local storage on the node