apiVersion: apps/v1
kind: Deployment
metadata:
  name: prysm-deployment
  labels:
    app: prysm
spec:
  selector:
    matchLabels:
      app: prysm
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: prysm
    spec:
      containers:
      - name: prysm
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        volumeMounts:
        - name: prysm-persistent-storage
          mountPath: /home/ubuntu
        - name: jwt-secret-volume
          mountPath: /secrets/jwtsecret
          subPath: jwtsecret
          readOnly: true 
        ports:
        - containerPort: 12000
          protocol: UDP
        - containerPort: 13000
          protocol: TCP
        - containerPort: 4000
          protocol: TCP
        - containerPort: 3500
          protocol: TCP
        - containerPort: 8585
          protocol: TCP
        args:
        - --accept-terms-of-use
        - --datadir=/home/ubuntu/eth_storage/prysm_storage
        - --rpc-host=0.0.0.0
        - --goerli
        - --grpc-gateway-host=0.0.0.0
        - --grpc-gateway-port=3500
        - --checkpoint-sync-url=https://goerli.beaconstate.info/
        - --genesis-beacon-api-url=https://goerli.beaconstate.info/
        - "--execution-endpoint=http://geth-service:8551"
        - --jwt-secret=/secrets/jwtsecret
        - --monitoring-host=0.0.0.0
        - --monitoring-port=8585
      volumes:
      - name: prysm-persistent-storage
        persistentVolumeClaim:
          claimName: prysm-pvc
      - name: jwt-secret-volume
        secret:
          secretName: jwt-secret